env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp"

task:
  name: "Project Testing..."
  timeout_in: 4h
  timeout: 4h
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G

  Download_ccache_script:
       - df -h
       - free -h
       - nproc
       - cat /etc/os*
       - env
       - cd /tmp
       - export CCACHE_DIR=/tmp/ccache
       - aria2c https://github.com/ccache/ccache/releases/download/v4.5.1/ccache-4.5.1.tar.gz
       - tar xf ccache-4.5.1.tar.gz
       - rm -rf ccache-4.5.1.tar.gz
       - ccache -s
       - top -b -i -n 1

  Sync_script:
       - cd /tmp/rom
       - repo init -q --no-repo-verify --depth=1 -u https://github.com/Spark-Rom/manifest -b spark -g default,-mips,-darwin,-notdefault
       - git clone https://github.com/NFS86/local_manifest --depth 1 -b aex-12 .repo/local_manifests
       - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

  timeout_in: 4h
  timeout: 4h
  Build_script:
       - cd /tmp/rom
       - . build/envsetup.sh
       - lunch spark_rosy-userdebug
       - ccache -M 20G
       - ccache -o compression=true
       - ccache -z
       - export ALLOW_MISSING_DEPENDENCIES=true
       - export TZ=Asia/Jakarta
       - export BUILD_USERNAME=finix
       - export BUILD_HOSTNAME=rosy
       - export WITH_GAPPS=false
       - mka bacon -j8
