task:
  name: "Project Testing..."
  timeout_in: 4h
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G
        
  Setup_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - wget https://raw.githubusercontent.com/AnGgIt88/GDIndex/master/worker/dist/worker.js
       - cp -fpr worker.js ~/.config/rclone/rclone.conf
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "NFS86"
       - git config --global user.email "jarbull86@gmail.com"
       - df -h
       - free -h
       - nproc
       - cat /etc/os*
       - cd /tmp
       - time aria2c https://roms.apon77.workers.dev/ccache/ci2/ccache.tar.gz -x16 -s50
       - time tar xf ccache.tar.gz
       - rm -rf ccache.tar.gz
 
  Ccache_Check_script:
      - ccache -s
      - top -b -i -n 1

  Sync_script:
      - cd /tmp/rom
      - repo init -q --no-repo-verify --depth=1 -u https://github.com/Spark-Rom/manifest -b spark -g default,-device,-mips,-darwin,-notdefault
      - git clone https://github.com/NFS86/local_manifest --depth 1 -b aex-12 .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)
