task:
  name: "Project Testing..."
  timeout_in: 240m
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - export DEBIAN_FRONTEND=noninteractive
       - mkdir -p ~/.config/rclone
       - wget https://raw.githubusercontent.com/AnGgIt88/GDIndex/master/worker/dist/worker.js
       - cp -fpr worker.js ~/.config/rclone/rclone.conf
       - echo "$rcloneconfig" > ~/.config/rclone/rclone.conf
       - DEBIAN_FRONTEND=noninteractive
       - git config --global user.name "NFS86"
       - git config --global user.email "jarbull86@gmail.com"
       - df -h
       - free -h
       - nproc
       - cat /etc/os*
       - cd /tmp
       - time aria2c https://roms.apon77.workers.dev/ccache/ci2/ccache.tar.gz -x16 -s50
       - time tar xf ccache.tar.gz
       - rm -rf ccache.tar.gz
 
  Ccache_Check_background_script:
      - export CCACHE_DIR=/tmp/ccache
      - ccache -s
      - top -b -i -n 1
