env:
    rcloneconfig: "ENCRYPTED[6b0db62450f6240a048544e10a2211d0aa37b084bcab8903a1aeb0c258bde0b7d07eeb9ef5f1e1f9ca9df586390dcf42]"
    TG_TOKEN: "ENCRYPTED[421c600e291ff261188086dedc688b89cba77c46a9339e88563a7fb2706250e612c44a17d8c43d42f7518e4fefd7296f]"
    TG_CHAT_ID: "ENCRYPTED[f047a07b7687296dffaad8848a522a4b1bd2ee404f5ef1d763debb2165fc7e999e19f2c274a55fd4254f27ee17527372]"
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp"
 
task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 3h
  timeout: 3h
  container:
      image: anggit86/dev:latest
      cpu: 8
      memory: 32G
        
  Build-Env-Setup_background_script:
       - ./env.sh

  Storage-Checker_background_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - ./sync.sh

  Build_script:
      - ./collect.sh
#      - ./final.sh

  Upload_script:
      - ./ziping.sh
#      - ./upload_rom.sh      
